SELECT DECODE(cd.TYPE_ID_USG, 21000, 'DTHD - Appel direct durée', 
21020, 'DTHD - Appels vers Publiphones (Direct)', 
21200, 'DTHD - Appel direct durée - Porté chez FT', 
21300, 'DTHD - Appel direct durée - Porté chez NUMERICABLE/CPTL', 
21400, 'DTHD - Appel direct durée - Porté chez autre', 
21705, 'DTHD - Appel Direct vers Porté Orange', 
21715, 'DTHD - Appel Direct vers Porté SFR', 
21725, 'DTHD - Appel Direct vers Porté Bouygues', 
21735, 'DTHD - Appel Direct vers Porté Guyane Mobile', 
21745, 'DTHD - Appel Direct vers Porté Martinique Mobile', 
21755, 'DTHD - Appel Direct vers Porté Réunion Mobile', 
22000, 'DTHD - Appel num. spéciaux impulsion', 
28000, 'DTHD - Renvoi d''appel', 
28200, 'DTHD - Renvoi d''appel - Porté chez FT', 
28300, 'DTHD - Renvoi d''appel - Porté chez NUMERICABLE/CPTL', 
28400, 'DTHD - Renvoi d''appel - Porté chez autre', 
28705, 'DTHD - Renvoi d''appel vers Porté Orange', 
28715, 'DTHD - Renvoi d''appel vers Porté SFR', 
28725, 'DTHD - Renvoi d''appel vers Porté Bouygues', 
28735, 'DTHD - Renvoi d''appel vers Porté Guyane Mobile', 
28745, 'DTHD - Renvoi d''appel vers Porté Martinique Mobile', 
28755, 'DTHD - Renvoi d''appel vers Porté Réunion Mobile',
61000, 'DTHD - Appel direct durée', 
61020, 'DTHD - Appels vers Publiphones (Direct)', 
61200, 'DTHD - Appel direct durée - Porté chez FT', 
61300, 'DTHD - Appel direct durée - Porté chez NUMERICABLE/CPTL', 
61400, 'DTHD - Appel direct durée - Porté chez autre', 
61705, 'DTHD - Appel Direct vers Porté Orange', 
61715, 'DTHD - Appel Direct vers Porté SFR', 
61725, 'DTHD - Appel Direct vers Porté Bouygues', 
61735, 'DTHD - Appel Direct vers Porté Guyane Mobile', 
61745, 'DTHD - Appel Direct vers Porté Martinique Mobile', 
61755, 'DTHD - Appel Direct vers Porté Réunion Mobile', 
62000, 'DTHD - Appel num. spéciaux impulsion', 
68000, 'DTHD - Renvoi d''appel', 
68200, 'DTHD - Renvoi d''appel - Porté chez FT', 
68300, 'DTHD - Renvoi d''appel - Porté chez NUMERICABLE/CPTL', 
68400, 'DTHD - Renvoi d''appel - Porté chez autre', 
68705, 'DTHD - Renvoi d''appel vers Porté Orange', 
68715, 'DTHD - Renvoi d''appel vers Porté SFR', 
68725, 'DTHD - Renvoi d''appel vers Porté Bouygues', 
68735, 'DTHD - Renvoi d''appel vers Porté Guyane Mobile', 
68745, 'DTHD - Renvoi d''appel vers Porté Martinique Mobile', 
68755, 'DTHD - Renvoi d''appel vers Porté Réunion Mobile',
'Autre type d''usage') AS Type_Trafic,
	   jcv.DISPLAY_VALUE AS Classe_Juridiction,
	   j.JURISDICTION AS Code_Juridiction,
	   d.DESCRIPTION_TEXT AS Libellé_Juridiction,
	   (bid.AMOUNT + bid.RATED_AMOUNT)/100 AS Euro_HT,
	   (bid.SECONDARY_AMOUNT)/100 AS Remise,
	   (bid.AMOUNT + bid.DISCOUNT)/100 AS HT_Remisé,
	   bid.COMPONENT_ID AS Nbre_appels,
	   bid.PACKAGE_ID AS Durée_en_s_ou_en_UT,
	   SUM(cd.SECOND_UNITS) AS Durée_en_s
FROM CDR_DATA cd, CDR_BILLED cb, JURISDICTIONS j, DESCRIPTIONS d, JURISDICTION_CLASS_VALUES jcv, BILL_INVOICE_DETAIL bid
WHERE cd.MSG_ID = cb.MSG_ID
AND cd.MSG_ID2 = cb.MSG_ID2
AND cd.MSG_ID_SERV = cb.MSG_ID_SERV
AND cd.CDR_DATA_PARTITION_KEY = cb.CDR_DATA_PARTITION_KEY
AND cd.SPLIT_ROW_NUM = cb.SPLIT_ROW_NUM
AND cb.BILL_REF_NO = numFact -- !! À MODIFIER !! /* numFac= numero de la facture qui servivra de mapping dans l'application*/
AND cb.BILL_REF_RESETS = 0
AND cd.JURISDICTION = j.JURISDICTION
AND jcv.JURISDICTION_CLASS = j.JURISDICTION_CLASS
AND jcv.LANGUAGE_CODE = 2
AND j.DESCRIPTION_CODE = d.DESCRIPTION_CODE
AND d.LANGUAGE_CODE = 2
AND cd.JURISDICTION = bid.RATE_TYPE
AND cd.TYPE_ID_USG = bid.SUBTYPE_CODE
AND bid.TYPE_CODE = 7 /* CDRs */
AND cb.BILL_REF_NO = bid.BILL_REF_NO
AND cb.BILL_REF_RESETS = bid.BILL_REF_RESETS
AND cb.BILL_INVOICE_ROW = bid.BILL_INVOICE_ROW
GROUP BY DECODE(cd.TYPE_ID_USG, 21000, 'DTHD - Appel direct durée', 
21020, 'DTHD - Appels vers Publiphones (Direct)', 
21200, 'DTHD - Appel direct durée - Porté chez FT', 
21300, 'DTHD - Appel direct durée - Porté chez NUMERICABLE/CPTL', 
21400, 'DTHD - Appel direct durée - Porté chez autre', 
21705, 'DTHD - Appel Direct vers Porté Orange', 
21715, 'DTHD - Appel Direct vers Porté SFR', 
21725, 'DTHD - Appel Direct vers Porté Bouygues', 
21735, 'DTHD - Appel Direct vers Porté Guyane Mobile', 
21745, 'DTHD - Appel Direct vers Porté Martinique Mobile', 
21755, 'DTHD - Appel Direct vers Porté Réunion Mobile', 
22000, 'DTHD - Appel num. spéciaux impulsion', 
28000, 'DTHD - Renvoi d''appel', 
28200, 'DTHD - Renvoi d''appel - Porté chez FT', 
28300, 'DTHD - Renvoi d''appel - Porté chez NUMERICABLE/CPTL', 
28400, 'DTHD - Renvoi d''appel - Porté chez autre', 
28705, 'DTHD - Renvoi d''appel vers Porté Orange', 
28715, 'DTHD - Renvoi d''appel vers Porté SFR', 
28725, 'DTHD - Renvoi d''appel vers Porté Bouygues', 
28735, 'DTHD - Renvoi d''appel vers Porté Guyane Mobile', 
28745, 'DTHD - Renvoi d''appel vers Porté Martinique Mobile', 
28755, 'DTHD - Renvoi d''appel vers Porté Réunion Mobile',
61000, 'DTHD - Appel direct durée', 
61020, 'DTHD - Appels vers Publiphones (Direct)', 
61200, 'DTHD - Appel direct durée - Porté chez FT', 
61300, 'DTHD - Appel direct durée - Porté chez NUMERICABLE/CPTL', 
61400, 'DTHD - Appel direct durée - Porté chez autre', 
61705, 'DTHD - Appel Direct vers Porté Orange', 
61715, 'DTHD - Appel Direct vers Porté SFR', 
61725, 'DTHD - Appel Direct vers Porté Bouygues', 
61735, 'DTHD - Appel Direct vers Porté Guyane Mobile', 
61745, 'DTHD - Appel Direct vers Porté Martinique Mobile', 
61755, 'DTHD - Appel Direct vers Porté Réunion Mobile', 
62000, 'DTHD - Appel num. spéciaux impulsion', 
68000, 'DTHD - Renvoi d''appel', 
68200, 'DTHD - Renvoi d''appel - Porté chez FT', 
68300, 'DTHD - Renvoi d''appel - Porté chez NUMERICABLE/CPTL', 
68400, 'DTHD - Renvoi d''appel - Porté chez autre', 
68705, 'DTHD - Renvoi d''appel vers Porté Orange', 
68715, 'DTHD - Renvoi d''appel vers Porté SFR', 
68725, 'DTHD - Renvoi d''appel vers Porté Bouygues', 
68735, 'DTHD - Renvoi d''appel vers Porté Guyane Mobile', 
68745, 'DTHD - Renvoi d''appel vers Porté Martinique Mobile', 
68755, 'DTHD - Renvoi d''appel vers Porté Réunion Mobile',
'Autre type d''usage'),
	   jcv.DISPLAY_VALUE,
	   j.JURISDICTION,
	   d.DESCRIPTION_TEXT,
	   bid.AMOUNT + bid.RATED_AMOUNT,
	   bid.SECONDARY_AMOUNT,
	   bid.AMOUNT + bid.DISCOUNT,
	   bid.COMPONENT_ID,
	   bid.PACKAGE_ID
ORDER BY 2, 3, 1